version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service

  add-service:
    build: ./addservice  # path is relative to docker-compose.yml location
    hostname: add-service
    ports:
      - 5051:5051  # host:container
    networks:
      sample:
        aliases:
          - add-service

  minus-service:
    build: ./minus-service  # path is relative to docker-compose.yml location
    hostname: minus-service
    ports:
      - 5052:5052  # host:container
    networks:
      sample:
        aliases:
          - minus-service
    
  multiply-service:
    build: ./multiply-service  # path is relative to docker-compose.yml location
    hostname: multiply-service
    ports:
      - 5053:5053  # host:container
    networks:
      sample:
        aliases:
          - multiply-service

  division-service:
    build: ./division-service  # path is relative to docker-compose.yml location
    hostname: division-service
    ports:
      - 5054:5054  # host:container
    networks:
      sample:
        aliases:
          - division-service
  # Add more services below
networks:
  sample: