version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service

  add-service:
    build: ./addservice  # path is relative to docker-compose.yml location
    hostname: add-service
    ports:
      - 5051:5051  # host:container
    networks:
      sample:
        aliases:
          - add-service

  minus-service:
    build: ./minus-service  # path is relative to docker-compose.yml location
    hostname: minus-service
    ports:
      - 7001:7001  # host:container
    networks:
      sample:
        aliases:
          - minus-service
    
  multiply-service:
    build: ./multiply-service  # path is relative to docker-compose.yml location
    hostname: multiply-service
    ports:
      - 5053:5053  # host:container
    networks:
      sample:
        aliases:
          - multiply-service

  division-service:
    build: ./division-service  # path is relative to docker-compose.yml location
    hostname: division-service
    ports:
      - 5054:5054  # host:container
    networks:
      sample:
        aliases:
          - division-service

  modservice:
    build: ./modservice  # path is relative to docker-compose.yml location
    hostname: modservice
    ports:
      - 5055:5055  # host:container
    networks:
      sample:
        aliases:
          - modservice
  exponentservice:
    build: ./exponentservice  # path is relative to docker-compose.yml location
    hostname: exponentservice
    ports:
      - 5056:5056  # host:container
    networks:
      sample:
        aliases:
          - exponentservice
  greater-than-service:
    build: ./greater-than-service  # path is relative to docker-compose.yml location
    hostname: greater-than-service
    ports:
      - 5057:5057  # host:container
    networks:
      sample:
        aliases:
          - greater-than-service
  less_than-service:
    build: ./less_than-service  # path is relative to docker-compose.yml location
    hostname: less_than-service
    ports:
      - 5058:5058  # host:container
    networks:
      sample:
        aliases:
          - less_than-service
  # Add more services below
networks:
  sample:
